### ISSUE TITLE
Random prefix

### ISSUE THREAD

**Issue by paulartjomow** [Prixix/RandomData#1]
Create a function that will return a prefix (Mr. / Mrs.) based on the argument gender and add a optional argument to fill the words (Mister / Misses)

**Comment by Ratnor** [comment]
Hey, I'd like to give this a try! This would be my first fix ever, and seems pretty reasonable. 

Just to get some clarity on the ask; would the arguments be something along the lines of :

`pickGender("male",false)`

such that you would receive:
`Mr.` as an output?

**Comment by paulartjomow** [comment]
> Hey, I'd like to give this a try! This would be my first fix ever, and seems pretty reasonable.
> 
> Just to get some clarity on the ask; would the arguments be something along the lines of :
> 
> `pickGender("male",false)`
> 
> such that you would receive:
> `Mr.` as an output?

Hey welcome to the open source community!
So you missunderstood something, when you type
`pickGender(false)`

The output could be
`Mr.` or
`Mrs.`


When you type
`pickGender(true)`

The output could be
`Mister` or
`Misses`



The gender is picked random (f.e. by using this.pickInt(0, 1) and 0 would be male and 1 would be female)

**Comment by Ratnor** [comment]
Hey submitted a PR! Please take a look when u get a chance! Cheers!

Also, whats the typical standard? As in, do you comment asking the owner to assign the issue and then submit a PR? or can you just submit it without having anyone assign an issue to you? (I mean I know I can, but should you?)

**Comment by paulartjomow** [comment]
Hey, thank you for your contribution!

It depends on the repo owner and the contribution rules. Most of the open repos have a file called "CONTRIBUTING.md", but if you don't know that then just ask.

Resolves #1
